# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: iprokofy <iprokofy@42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/26 09:02:32 by iprokofy          #+#    #+#              #
#    Updated: 2017/08/26 09:02:34 by iprokofy         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = *.c
NAME = eval_expr

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)