# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: iprokofy <iprokofy@42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/21 13:44:05 by iprokofy          #+#    #+#              #
#    Updated: 2017/08/21 13:44:07 by iprokofy         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ft_do_op.c ft_str.c ft_func.c
NAME = do-op

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	rm -f $(NAME)
