# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: iprokofy <iprokofy@42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/23 12:39:09 by iprokofy          #+#    #+#              #
#    Updated: 2017/08/23 12:39:11 by iprokofy         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ft_tail.c ft_str.c
NAME = ft_tail

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC) 

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)